### ISSUE TITLE
Request for membership

### ISSUE THREAD

**Issue by kanitsharma** [mostjs-community/about#11]
Hey guys, huge fan of this library :heart: .
I am working on a frontend framework that's built with @most/core at its heart, its currently in its early stages right now and in a private repo. It would be awesome if I will be able make it a part of this community.

By the way I also just submitted a PR to redux-most, updating it to @most/core.
https://github.com/joshburgess/redux-most/issues/31

I would love to contribute to this community.

**Comment by TylorS** [comment]
Hello @kanitsharma ! It's a pleasure to meet you. I've sent you and invite via email - let us know if you have any issues. 

Feel free to join us in gitter (https://gitter.im/cujojs/most) if you have questions or anything to share with us really! Welcome 😄
