### ISSUE TITLE
Request for Membership

### ISSUE THREAD

**Issue by carloszimm** [mostjs-community/about#12]
Hi guys!
I have some operators based on Rx that I'm thinking about exporting them in a package (: Is that the right place for requesting to become a member of the community?

**Comment by briancavalier** [comment]
Hey @cezl.  Absolutely, this is the right place.  We appreciate your interest and contributions!  I sent you an invite to the GitHub org.  Let us know if you don't get it, or have any trouble joining.

**Comment by carloszimm** [comment]
Invite received and accepted. Thanks @briancavalier !

**Comment by briancavalier** [comment]
👍 My pleasure.
