### ISSUE TITLE
Request for Membership

### ISSUE THREAD

**Issue by gitusp** [mostjs-community/about#13]
As I mentioned on https://github.com/mostjs/core/issues/279, I completed `exhaustMap` [on my repository](https://github.com/gitusp/exhaustMap/tree/exhaustMap).
Now, I'd like to publish the package as `mostjs-community/exhaust-map`.

I would love to contribute to this community.
Thank you.

**Comment by briancavalier** [comment]
Hey @gitusp.  I just sent you an invite.  Thank you for getting involved and contributing to mostjs-community!
