### ISSUE TITLE
Request for membership

### ISSUE THREAD

**Issue by semmel** [mostjs-community/about#14]
I did some work to [update mostjs-community/subject to @most/core v1+](https://github.com/mostjs-community/subject/pull/50)

I like that I can use the nice api of mostjs streams for reactive programming using a *focused* library.  I feel using [`effect/Stream`](https://effect.website/docs/guides/streaming/stream), I had to commit to the whole [effect framework](https://effect.website). 

I'd like to contribute more integration code in the future.

Thanks for considering! 😄

**Comment by briancavalier** [comment]
Hey @semmel, awesome!  It's great to have you in the community.  I just sent you an invite.
