### ISSUE TITLE
I'd like to contribute! 

### ISSUE THREAD

**Issue by Globolobo** [mostjs-community/about#2]
Hey guys, I've been playing around with this repo a little and would like to get added

**Comment by briancavalier** [comment]
Awesome, thanks @Globolobo!  I just sent you an invite to the github org.  Let me know if you have any trouble accepting it.  We're still working out some of the details and permissions, so bear with us if things seem to change over the next few days or weeks.  We'll also be posting more details about process for contributing, managing repos, etc etc., so keep an eye out for those things.

We're def glad to have you in the community!
