### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by brandonpayton** [mostjs-community/about#3]
Thanks for setting this up! I'd like to be a member and to help as I'm able.

**Comment by briancavalier** [comment]
Great! Just sent you an invite, @brandonpayton.

We're still working out some of the details and permissions, so bear with us if things seem to change over the next few days or weeks. We'll also be posting more details about process for contributing, managing repos, etc etc., so keep an eye out for those things.

**Comment by brandonpayton** [comment]
Understood. Thanks for the invite!
