### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by mariuslundgard** [mostjs-community/about#4]
Hey @briancavalier, I’d like to contribute :-) At the moment I’m playing with `most-w3msg` and could send a pull request to upgrade most (or make it a peer dependency perhaps?).

**Comment by briancavalier** [comment]
Hey @mariuslundgard, awesome.  We'll send you an invite.

Updating most-w3msg would be very much appreciated!

**Comment by mariuslundgard** [comment]
Great! I just attempted to push changes to a `mariuslundgard/update` branch, but I don't have permissions. Would it be possible to move `most-w3msg` to the community organization?

**Comment by briancavalier** [comment]
Sorry for any confusion.  We're still working out some of the details and permissions, so bear with us if things seem to change over the next few days or weeks. We'll also be posting more details about process for contributing, managing repos, etc etc., so keep an eye out for those things.

> Would it be possible to move most-w3msg to the community organization?

That's definitely something we're planning to do.  Thanks for sending https://github.com/cujojs/most-w3msg/pull/7 in the meantime!
